server:
  port: 8888

coffeenet:
  application-name: 'CoffeeNet Config Server'
  profile: integration
  security:
    enabled: false
  discovery:
    instance:
      home-page-url: http://localhost:8888
      hostname: localhost
    client:
      service-url:
        defaultZone: http://coffeenet-discovery.coffeenet:8761/eureka/
  logging:
    console:
      enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://coffeenet-auth.coffeenet:9999/user

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: 'file:/configs/{application}/{profile}'