version: '2'
services:
  config-server:
    image: coffeenet/coffeenet-config-server:latest
    volumes:
      - ./coffeenet-config-server/application.yml:/application.yml
      - ./coffeenet-config-server/configs:/configs
    ports:
      - '8888:8888'
    hostname: coffeenet-config-server.coffeenet

  discovery:
    image: coffeenet/coffeenet-discovery:latest
    volumes:
      - ./coffeenet-discovery/application.yml:/application.yml
    ports:
      - '8761:8761'
    hostname: coffeenet-discovery.coffeenet

  auth:
    image: coffeenet/coffeenet-auth:latest
    volumes:
      - ./coffeenet-auth/application.yml:/application.yml
    ports:
      - '9999:9999'
    hostname: coffeenet-auth.coffeenet
    links:
      - discovery:coffeenet-discovery.coffeenet
      - ldap:coffeenet-ldap.coffeenet
      - graylog:coffeenet-logging.coffeenet
      - mariadb:mariadb.coffeenet
    depends_on:
      - ldap
      - mariadb
  ldap:
    build: ./ldap-ds-389/
    ports:
      - '38900:389'
    hostname: coffeenet-ldap.coffeenet
  mariadb:
    build: ./mariadb/
    ports:
      - '3308:3306'
    hostname: mariadb.coffeenet

  mongo:
    image: 'mongo:3'
  elasticsearch:
    image: 'elasticsearch:2'
    command: 'elasticsearch -Des.cluster.name="graylog"'
  graylog:
    image: graylog2/server:2.2.3-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - '9000:9000'
      - '12201/udp:12201/udp'
    hostname: coffeenet-logging.coffeenet
