version: '2.3'
services:
  config-server:
    image: coffeenet/coffeenet-config-server:latest
    container_name: coffeenet-config-server
    volumes:
      - ./coffeenet-config-server/application.yml:/application.yml
      - ./coffeenet-config-server/configs:/configs
    ports:
      - '8888:8888'
    hostname: coffeenet-config-server.coffeenet
    links:
      - discovery:coffeenet-discovery.coffeenet
      - auth:coffeenet-auth.coffeenet
    depends_on:
      auth:
        condition: service_healthy
      discovery:
        condition: service_started
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
       interval: 10s
       timeout: 3s
       retries: 5

  discovery:
    image: coffeenet/coffeenet-discovery:latest
    container_name: coffeenet-discovery
    volumes:
      - ./coffeenet-discovery/application.yml:/application.yml
    ports:
      - '8761:8761'
    hostname: coffeenet-discovery.coffeenet
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
       interval: 10s
       timeout: 3s
       retries: 5

  auth:
    image: coffeenet/coffeenet-auth:latest
    container_name: coffeenet-auth
    volumes:
      - ./coffeenet-auth/application.yml:/application.yml
    ports:
      - '9999:9999'
    hostname: coffeenet-auth.coffeenet
    links:
      - discovery:coffeenet-discovery.coffeenet
      - ldap:coffeenet-ldap.coffeenet
      - auth-mariadb:auth-mariadb.coffeenet
    depends_on:
      auth-mariadb:
        condition: service_healthy
      ldap:
        condition: service_started
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:9999/login"]
       interval: 10s
       timeout: 3s
       retries: 5

  auth-mariadb:
    build: coffeenet-auth-mariadb/
    container_name: coffeenet-auth-mariadb
    ports:
      - '3308:3306'
    hostname: auth-mariadb.coffeenet
    healthcheck:
      test: "/usr/bin/mysql --user=auth --password=auth --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  ldap:
    build: ./ldap-ds-389/
    container_name: coffeenet-ldap
    ports:
      - '38900:389'
    hostname: coffeenet-ldap.coffeenet

  mongodb:
    image: 'mongo:3'
    container_name: coffeenet-graylog-mongodb
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.5.1'
    container_name: coffeenet-graylog-elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog:
    image: 'graylog/graylog:2.3.0-1'
    container_name: coffeenet-graylog
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    hostname: coffeenet-logging.coffeenet