coffeenet:
  application-name: Startseite
  profile: integration
  security:
    client:
      client-id: coffeeNetClient
      client-secret: coffeeNetClientSecret
      access-token-uri: http://coffeenet-auth.coffeenet:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/authorize
    logout-success-url: http://localhost:9999/logout
    resource:
      user-info-uri: http://coffeenet-auth.coffeenet:9999/user
  discovery:
    instance:
      home-page-url: http://localhost:8081
      hostname: localhost
      non-secure-port: '8081'
    client:
      service-url:
        defaultZone: http://coffeenet-discovery.coffeenet:8761/eureka/
  logging:
    console:
      enabled: true
    gelf:
      server: coffeenet-logging.coffeenet
      enviroment: docker

spring:
  data:
    mongodb:
      host: coffeenet-frontpage-mongodb.coffeenet
      port: 27017
      username: frontpage
      password: frontpage
      authentication-database: admin
      database: frontpage
